# Generated by Django 4.2.7 on 2024-04-21 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(default='TS08AA0000', max_length=10)),
                ('bus_name', models.CharField(default='RTC', max_length=100)),
                ('ticket_fare', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('arrival_time', models.TextField(default='5.00')),
                ('fromdesti', models.CharField(default=None, max_length=100)),
                ('todesti', models.CharField(default=None, max_length=500)),
                ('place_notes', models.TextField(blank=True, default='Interesting place to visit', null=True)),
                ('bus_image', models.ImageField(blank=True, null=True, upload_to='bus_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, max_length=255, null=True)),
                ('to_location', models.CharField(blank=True, max_length=255, null=True)),
                ('passenger_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('payment_mode', models.CharField(blank=True, default=1, max_length=20, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('qr_code_image', models.BinaryField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
